<?php

namespace SchoolBundle\Repository;

/**
 * TravailaFaire
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravailaFaireRepository extends \Doctrine\ORM\EntityRepository
{
}
