payment:
    resource: "@PaymentBundle/Controller/"
    type:     annotation
    prefix:   /

school:
    resource: "@SchoolBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

use:
    resource: '@UserBundle/Controller/'
    type: annotation
    prefix:   /{_locale}/

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}/

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix:   /{_locale}/