<?php

namespace PaymentBundle\Repository;

/**
 * PaymentRestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRestoRepository extends \Doctrine\ORM\EntityRepository
{
}
